src/shared/GlobalStyle.tsx
> scroll style 추가
> global style에 scroll style 추가
=> Add scroll style

src/components/InformationPage/index.tsx, src/components/InformationPage/style.ts, src/pages/information.tsx
> 절차 설명 페이지를 제작했습니다
> 절차 설명 페이지 제작
=> 절차 설명 페이지 퍼블리싱

packages/hello-gsm/src/components/ApplicationPage/index.tsx, packages/hello-gsm/src/components/Common/Header/index.tsx, packages/hello-gsm/src/components/FAQPage/index.tsx, packages/hello-gsm/src/pages/faq.tsx
> 배포를 위한 develop 브랜치의 변경사항 입니다
> 빌드가 안되던 이슈 수정
=> Update for deploy develop

packages/hello-gsm/public/data/about.ts, packages/hello-gsm/src/components/AboutPage/index.tsx
> about 페이지 수정
- backend description 수정
- devops -> 서채운선배 데이터 수정 
아직 수정사항이 남아 있을수도 있으니 pr만 열어두고  merge는 추후에 하는건 어떨까요??
=> Update about data

packages/hello-gsm/src/components/Common/Header/index.tsx
> 회원가입에 유저가 직접 접근할 필요가 없어짐에 따라 header를 수정하였습니다
> header의 회원가입 삭젝
=> Update header style

packages/hello-gsm/src/Api/application.ts, packages/hello-gsm/src/Api/auth.ts, packages/hello-gsm/src/Api/user.ts, packages/hello-gsm/src/Utils/Libs/requestApi.ts, packages/hello-gsm/src/components/SignInPage/index.tsx, packages/hello-gsm/src/components/SignInPage/style.ts, packages/hello-gsm/src/shared/config.ts, packages/hello-gsm/src/type/application.ts, packages/hello-gsm/src/type/signup.ts
> api 연동을 위한 작업을 진행했습니다
> - requestApi : axios 설정
> - requestUrls : 요청을 보낼 경로들
> - Api/* : api들
=> api 연동을 위한 작업

packages/hello-gsm-admin/src/pages/_app.tsx, packages/hello-gsm-admin/tsconfig.json, packages/hello-gsm/src/components/AboutPage/index.tsx, packages/hello-gsm/src/components/FAQBox/index.tsx, packages/hello-gsm/src/components/FAQModal/index.tsx, packages/hello-gsm/src/components/FAQPage/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/components/MypageModal/index.tsx, packages/hello-gsm/src/components/MypagePage/index.tsx, packages/hello-gsm/src/components/NotFoundPage/index.tsx, packages/hello-gsm/src/components/SignUpPage/index.tsx, packages/hello-gsm/src/pages/_app.tsx, packages/hello-gsm/tsconfig.json
> public alias 세팅 하였습니다.
- 상대경로 -> 절대경로로 수정
- public alias 추가
=> public alias 세팅

packages/hello-gsm/src/components/SignUpPage/index.tsx
>  회원가입 후 라우트 위치 수정
/mypage -> /auth/signin
=> Update router replace

packages/hello-gsm/src/components/SchoolPage/index.tsx
> user status test
> mypage의 getServerSideProps에서 이슈가 있어 client side rendering으로 체킹하고자 합니다
=> Add get test

packages/hello-gsm/src/components/SchoolPage/index.tsx, packages/hello-gsm/src/pages/mypage.tsx
> mypage test
> getServerSideProps에서 요청이 안되는 이슈 해결 테스트
=> Remove redirect

packages/hello-gsm/src/components/MypagePage/index.tsx, packages/hello-gsm/src/pages/mypage.tsx
> data 객체를 보기위한 코드 삽입
> console에 data 출력
=> Add res value log

packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/components/MainPageDescription/style.ts
> 메인 페이지의 전반적 디자인 반영
> 메인 페이지 디자인 수정 내용들을 반영했습니다
=> 메인 페이지 스타일 수정

packages/hello-gsm/src/PageContainer/FAQPage/index.tsx, packages/hello-gsm/src/components/Common/Header/index.tsx
> header 디자인 수정을 하였습니다
> header nav 순서 변경
> faqpage의 error.response에 옵셔널 체이닝 추가
=> Header 디자인 수정

packages/hello-gsm/src/PageContainer/SignUpPage/style.ts
> 회원가입 페이지 수정
- 윈도우에서 회원가입 input 사이즈 오류 수정
- 개인정보 약관컴포넌트 스크롤바 수정
=> Update  style

packages/hello-gsm/src/components/Common/Header/style.ts
> header 로그아웃 button 높이 수정
> 로그아웃 button이 다른 컨텐츠와 줄 높이가 맞지 않는 문제를 해결했습니다
=> Add button margin init

packages/hello-gsm/src/PageContainer/FAQPage/index.tsx
> faq issue fix
> faq를 업데이트하는 로직을 수정하였습니다
=> Update setFaqList logic

packages/hello-gsm/src/pages/auth/signin.tsx
> 로그인 한 유저는 로그인 페이지에 접근 불가
- Signin ServerSideProps 추가
- refreshToken || accessToken이 있을 시 main 페이지로 이동
=> Signin SSR 추가

packages/hello-gsm/src/PageContainer/MainPage/index.tsx
> mainpage PC 판별 기본값 변경
> isPC state의 default value를 true로 변경하였습니다
=> Update isPC default value

packages/hello-gsm/src/pages/index.tsx, packages/hello-gsm/src/pages/mypage.tsx
> SEOHelmet에 들어가는 page의 description을 수정했습니다
> - main page
> - mypage
=> Update seo description

packages/hello-gsm/src/components/Modals/GEDScoreResultModal/index.tsx, packages/hello-gsm/src/components/Modals/ScoreResultModal/index.tsx
=> Update confirm content

packages/hello-gsm/src/components/Common/Header/style.ts
=> Add center

packages/hello-gsm/src/PageContainer/GEDCalculatorPage/index.tsx, packages/hello-gsm/src/components/Modals/GEDScoreResultModal/index.tsx, packages/hello-gsm/src/components/Modals/GEDScoreResultModal/style.ts, packages/hello-gsm/src/type/score.ts
> 검정고시 학생 공식이 조금 변경되어 코드도 수정되었습니다.
- 결과창 환산총점 추가
- 환산총점 공식 추가 (scoreTotal)
=> 검정고시 학생 공식 변경

packages/hello-gsm/src/PageContainer/MainPage/index.tsx
> 테스트 기간 중 사용자들이 실제 입학 지원으로 착오함을 미연에 방지 하기 위한 멘트 수정
> ApplyTerm의 멘트 수정
=> Update ApplyTerm text

packages/hello-gsm/src/components/MainPageDescription/index.tsx
> 메인페이지의 description을 수정했습니다
> 메인페이지 description 수정
=> Update mainpage description

packages/hello-gsm-calculate/src/PageContainer/GEDCalculatorPage/style.ts, packages/hello-gsm/src/PageContainer/GEDCalculatorPage/style.ts
> 검정고시 성적 입력 스타일을 수정하였습니다.
윈도우 해상도로 보면 화면이 꽉 차보여 px단위에서 vh단위로 바꾸어 유동적으로 보이게끔 하였습니다.
=> Update px -> vh

packages/hello-gsm/src/components/Modals/FAQModal/style.ts
> FAQModal 반응형 이슈 해결
> FAQModal의 반응형을 추가했습니다
=> faq responsive design

packages/hello-gsm/src/pages/test.tsx
> test 페이지 삭제
> 테스트를 진행했던 test 페이지를 삭제했습니다
=> Remove test.tsx

packages/hello-gsm/src/pages/index.tsx
> mainpage issue 해결
> mainpage useEffect에 누락된 dependency array를 추가했습니다.
=> Add dependency array

packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx
> Apply page의 이미지가 등록되지 않았을 때 toast error를 추가하였습니다
> toast error 추가
=> apply page not image toast error

packages/hello-gsm/src/components/Common/Header/index.tsx
> 로그아웃 로직 변경
> 로그아웃 요청 후 logged 상태 변환이 가끔 안되는 이슈가 있어 새로고침 형식으로 변경하였습니다
=> logout 로직 변경

packages/hello-gsm/src/PageContainer/MypagePage/index.tsx, packages/hello-gsm/src/PageContainer/MypagePage/style.ts
> 원서 제출 후 마이페이지로 이동 시 상태가 제대로 업데이트 되지 않는 경우가 존재하여 새로고침을 유도함
> 원서가 없는 유저의 마이페이지에 새로고침을 유도하는 문구를 추가하였습니다
=> 마이페이지 새로고침 유도

packages/hello-gsm/src/PageContainer/Test/CalculatorPage/index.tsx
> 비교과 성적 입력할 때 음수가 입력 안되게 하였습니다.
- validate 추가
=> 비교과 성적 입력 음수 예외처리

packages/hello-gsm/src/components/InformationDescription/index.tsx, packages/hello-gsm/src/components/InformationDescription/style.ts
> information page의 `원서 및 성적 작성` 부분의 멘트를 수정하였습니다
> `원서 및 성적 작성` 멘트 수정
=> Update information description

packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/PageContainer/ManualPage/index.tsx, packages/hello-gsm/src/PageContainer/index.tsx, packages/hello-gsm/src/components/BubbleButton/index.tsx, packages/hello-gsm/src/components/BubbleButton/style.ts, packages/hello-gsm/src/components/index.tsx, packages/hello-gsm/src/pages/manual.tsx
> 메뉴얼 페이지 추가
- BubbleButton 컴포넌트화
- ManualPage 추가
- 전체화면
- laptop
- tablet
- mobile
=> Add ManualPage

packages/hello-gsm/src/pages/apply.tsx, packages/hello-gsm/src/pages/calculator/ged.tsx, packages/hello-gsm/src/pages/calculator/index.tsx, packages/hello-gsm/src/pages/information.tsx, packages/hello-gsm/src/shared/acceptable.ts
> 접수기간에만 페이지 접근하게 하였습니다.
- date ssr 추가
**어차피 지금 테스트 기간이라 바로 머지는 불가하니 이 방식이 괜찮은지만 리뷰 부탁드려요! 
이 방식이 채택되면 다른 페이지도 ssr 추가하겠습니다.**
=> 성적입력 기간 설정

packages/hello-gsm/src/middleware.ts, packages/hello-gsm/src/pages/apply.tsx, packages/hello-gsm/src/pages/calculator/ged.tsx, packages/hello-gsm/src/pages/calculator/index.tsx, packages/hello-gsm/src/pages/information.tsx, packages/hello-gsm/src/shared/acceptable.ts
> 접수 가능 기간에만 페이지에 접근 가능하도록 하는 기능을 업데이트 했습니다
> middleware에 acceptable에 따라 접근 가능 여부 추가
> middleware 전체적인 리펙토링
=> Update acceptable handling

packages/hello-gsm/src/components/Modals/FAQModal/style.ts, packages/hello-gsm/src/components/Modals/FindSchoolModal/style.ts
> faqModal과 FindSchoolModal의 스크롤바의 디자인을 변경하였습니다
=> Update Scrollbar design

packages/hello-gsm/src/pages/404.tsx
> 404 페이지에서 ssr을 추가하였습니다.
- 로그인 여부 판별을 위해 ssr 추가
=> Add 404Page SSR

packages/hello-gsm/src/pages/404.tsx
- 404 페이지에서 ssr 작업을 삭제하였습니다.
https://nextjs.org/docs/messages/404-get-initial-props
=> Delete 404 ssr

packages/hello-gsm/src/Assets/svg/InspectionIcon.tsx, packages/hello-gsm/src/PageContainer/InspectionPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/type/user.ts
> mainpage의 지원 기간 외의 디자인을 추가하였고, 상태가 아닌 변수로 관리할 부분을 업데이트 했습니다.
=> Update mainPage state

packages/hello-gsm-admin/src/PageContainer/TicketPage/index.tsx, packages/hello-gsm/src/PageContainer/ApplicationPage/index.tsx, packages/hello-gsm/src/PageContainer/ManualPage/index.tsx
> 메뉴얼 페이지 스크롤바 추가 하였습니다
- 스크롤 추가
- 인쇄 기능 수정
=> Add manual scroll

packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/components/MainPageDescription/style.ts
> 원서 접수 버튼이 해상도에 따라 잘 보이지 않아 단위를 수정하였습니다.
- px -> vh
=> Update margin-top px -> vh

packages/hello-gsm/src/middleware.ts
> middleware의 acceptable 관리 방법 변경
> middleware 시간대에 맞게끔 기존 시간에서 9시를 빼주었다
=> Update middleware acceptable

packages/hello-gsm/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/GEDCalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/GEDCalculatorPage/index.tsx
> 예외처리 추가
- 비교과 성적 입력 부분 음수 예외처리 추가
https://www.hellogsm.kr/calculator/test
모의 성적 입력 코드에는 적용이 되어있어 저기서 테스트 해보시면 됩니다.
=> Add validate

packages/hello-gsm/src/components/InformationDescription/index.tsx
> 절차설명 페이지 내용 수정
- 절차설명 페이지 내용 수정 @hyeongrok7874
=> Release v1.3.2

packages/hello-gsm/src/PageContainer/MypagePage/index.tsx
=> Update Content css condition

packages/hello-gsm/src/PageContainer/SignInPage/index.tsx, packages/hello-gsm/src/PageContainer/SignInPage/style.ts
=> Update login button desc

packages/hello-gsm/src/PageContainer/MainPage/index.tsx
> 메인 페이지 이슈 해결
> 메인 페이지 이슈 해결했습니다
=> Remove error style

packages/hello-gsm/src/PageContainer/MypagePage/index.tsx
> 마이페이지의 스타일 에러를 해결했습니다
> 마이페이지 스타일 에러 해결
=> Update error style

packages/hello-gsm/src/middleware.ts
=> Update safari browser

packages/hello-gsm-calculate/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/CalculatorPage/index.tsx
사용자가 알아볼 수 있게 성적 입력 페이지에서 봉사활동(시간)입력으로 수정
- 봉사활동 -> 봉사활동(시간)
=> Add time desc

packages/hello-gsm/src/middleware.ts
모바일에서는 사파리 접속이 돼서 조건식을 조금 수정하였습니다.
- if 조건식 추가 (Mobile Safari)
=> Update middleware 조건식 수정

packages/hello-gsm-admin/src/Api/application.ts, packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/PageContainer/MainPage/style.ts, packages/hello-gsm-admin/src/Types/application.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts, packages/hello-gsm-admin/src/components/ContentBox/index.tsx, packages/hello-gsm-admin/src/pages/index.tsx
=> Add applicants count

packages/hello-gsm-admin/src/Api/application.ts, packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/PageContainer/MainPage/style.ts, packages/hello-gsm-admin/src/Types/application.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts, packages/hello-gsm-admin/src/components/ContentBox/index.tsx, packages/hello-gsm-admin/src/pages/index.tsx
> Release v1.3.5
FAQ 내용 수정 
사파리 브라우저 이슈 핫픽스
Date 이슈 핫픽스 
날짜 수정 
최종 제출 인원 표시 기능 추가
=> Release v1.3.5

packages/hello-gsm-admin/src/components/ContentBox/index.tsx
> 서류제출여부 초기 값 할당 로직 변경
> prop을 direct로 state에 할당하는 방식으로 관리자에 issue가 생겨 useEffect에서 할당해주는 방식으로 변경했습니다!
=> Update documentReception state

packages/hello-gsm/src/PageContainer/MainPage/index.tsx
> mobile main 페이지 state 적용
> acceptable state로 변경 당시 누락된 부분 업데이트
=> Update acceptable -> isAcceptable

packages/hello-gsm/src/shared/acceptable.ts
> cross browsing issue가 있어 acceptable의 new Date에 넘겨주는 날짜의 format을 변경하였습니다
> shared/acceptable format 수정
=> Update acceptable new Date format

packages/hello-gsm-admin/src/components/ContentBox/index.tsx
> 관리자 검색 시 2차 점수 업데이트 누락 이슈 해결
> 지원자 검색 시 2차 점수가 제대로 반영되지 않는 문제 해결했습니다
=> Add setScore useEffect

packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/components/MainPageDescription/style.ts
> 메인 페이지의 설명부의 최종 결과에 최종 학과를 포함 시켰습니다.
데스크톱
태블릿
모바일
=> [Hotfix] mainDescription majorResult

packages/hello-gsm/src/components/MainPageDescription/index.tsx
> 최종 결과의 학과가 나오지 않는 이슈 해결 중
> props로 최종 학과를 보여줬지만 상태가 제대로 반영되지 않는 것 같아 prop를 받아와 state로 관리해보겠습니다
=> Update majorResult handling

packages/hello-gsm/public/data/about.ts
about 페이지 수정
pc버전
모바일 버전
태블릿 버전
about페이지를 수정하였습니다
=> about 페이지 수정

packages/hello-gsm/src/PageContainer/AboutPage/index.tsx, packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm/src/PageContainer/BrowserPage/index.tsx, packages/hello-gsm/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/ChoosePage/index.tsx, packages/hello-gsm/src/PageContainer/FAQPage/index.tsx, packages/hello-gsm/src/PageContainer/GEDCalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/InformationPage/index.tsx, packages/hello-gsm/src/PageContainer/InformationPage/style.ts, packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/PageContainer/ManualPage/index.tsx, packages/hello-gsm/src/PageContainer/MypagePage/index.tsx, packages/hello-gsm/src/PageContainer/NotFoundPage/index.tsx, packages/hello-gsm/src/PageContainer/SchoolPage/index.tsx, packages/hello-gsm/src/PageContainer/SignInPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/GEDCalculatorPage/index.tsx, packages/hello-gsm/src/middleware.ts, packages/hello-gsm/src/pages/_app.tsx, packages/hello-gsm/src/pages/apply.tsx
> 원서 페이지와 성적 계산 페이지를 통합했습니다.
- pages/apply.tsx에서 step 단계마다 페이지 노출
[참고자료](https://www.youtube.com/watch?v=NwLWX2RNVcw&t=61s&ab_channel=%ED%86%A0%EC%8A%A4)
- 새로고침 및 뒤로가기 시 경고창
- Header -> _app.tsx 로 이동
=> [Client] Intergrated Apply Page

packages/hello-gsm-admin/src/Api/application.ts, packages/hello-gsm-admin/src/Api/auth.ts, packages/hello-gsm-admin/src/Api/identity.ts, packages/hello-gsm-admin/src/Api/user.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts, packages/hello-gsm/src/Api/application.ts, packages/hello-gsm/src/Api/auth.ts, packages/hello-gsm/src/Api/identity.ts, packages/hello-gsm/src/Api/user.ts, packages/hello-gsm/src/Utils/Libs/requestUrls.ts, packages/hello-gsm/src/type/application.ts, packages/hello-gsm/src/type/signup.ts
> API path등을 수정하였습니다.
> API 명세서대로 기존의 API들을 수정, 추가, 삭제 하였습니다.
[명세서 링크](https://api.dev.hellogsm.kr/docs/index.html#_%EA%B0%9C%EC%9A%94)
+ MajorType : 학과 타입
+ GraduationStatusType : 졸업 상태 타입
+ ScreeningType : 입학 전형 타입
+ EvaluationStatusType : 시험 결과 상태 타입
+ CommonApplicationResponseType : 공통 원서 정보 반환 타입
+ GEDApplicationResponseType : 검정고시 학생의 경우 원서 정보 반환 타입 (CommonApplicationResponseType을 상속)
+ ApplicationResponseType : 졸업 예정, 졸업 학생의 경우 원서 정보 반환 타입 (CommonApplicationResponseType을 상속)
+ ApplyFormType : 원서 제출 타입
리뷰 하실 때에 네이밍, application api 파일 위주로 검사해주시면 감사하겠습니다!
=> [API] set API 

packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/style.ts
> 휴대전화번호 인증 부분을 퍼블리싱 하였습니다.
+ input 내의 간격을 조정하였습니다. `32px -> 16px`
---
=> [Client] Add Certificate PhoneNumber

packages/hello-gsm-admin/src/PageContainer/SignInPage/style.ts, packages/hello-gsm-admin/src/components/PrintButton/style.ts, packages/hello-gsm/src/PageContainer/AboutPage/style.ts, packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm/src/PageContainer/ApplyPage/style.ts, packages/hello-gsm/src/PageContainer/SignInPage/style.ts, packages/hello-gsm/src/components/ApplyBarBox/index.tsx, packages/hello-gsm/src/components/ApplyBarBox/style.ts, packages/hello-gsm/src/components/Modals/DepartmentModal/index.tsx, packages/hello-gsm/src/pages/apply.tsx, packages/hello-gsm/src/type/application.ts
> 특별전형 선택창을 추가하고, 각종 에러를 해결했습니다.
- 특별전형 클릭 시 세부 전형 클릭창 보여지기
- 특별전형 클릭 시 왼쪽 bar, 에러 메세지 스타일링 변경
- 1순위, 2순위, 3순위 학과 값이 1순위 학과 값으로 설정되었던 에러 해결
- 과 선택시 반영이 되지 않았던 에러 해결
- ssr 데이터 객체가 올바르지 않았던 에러 해결
=> [Client] Add Special Screening

packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/components/ListHeader/index.tsx, packages/hello-gsm-admin/src/pages/index.tsx
> 지원자 원서 검색기능을 제작했습니다.
루트 경로에서 테스트 가능합니다.
https://github.com/themoment-team/hello-gsm-front/assets/106712562/a1a45917-876c-4ddd-8ac9-dea8df3a6273
리뷰 후 더미데이터, 테스트에 필요한 코드 제거하겠습니다.
=> [Admin] search applicationList

packages/hello-gsm/src/components/Modals/FindSchoolModal/index.tsx
> 학교 검색 필터 수정
- before
> 필터 후 map
- after
> 데이터를 받은 다음 filter
=> [Client] schoolFilter error fix

packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/components/Common/Footer/style.ts, packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/components/MainPageDescription/style.ts, packages/hello-gsm/src/components/Modals/MainResultModal/index.tsx, packages/hello-gsm/src/components/SideBar/style.ts
> 모바일 반응형 작업을 하였습니다.
- 사이드바 반응형 추가
- footer 반응형 추가  
- 메인 페이지 반응형 추가
=> [Client] Mobile Responsive

packages/hello-gsm/src/Api/identity.ts, packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm/src/PageContainer/InformationPage/index.tsx, packages/hello-gsm/src/PageContainer/MypagePage/index.tsx, packages/hello-gsm/src/PageContainer/SignInPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/style.ts, packages/hello-gsm/src/Utils/Libs/requestApi.ts, packages/hello-gsm/src/hooks/useGetLogged.ts, packages/hello-gsm/src/pages/index.tsx, packages/hello-gsm/src/type/signup.ts
> 회원가입 api를 연동했습니다.
- api post key 수정(phonNumber -> phoneNumber) - https://github.com/themoment-team/hello-gsm-front/pull/248/commits/09b42ac6453e398dd5679b7af068830dc5360265
- 원서 이미지 업로드 에러 수정(photo -> file) - https://github.com/themoment-team/hello-gsm-front/pull/248/commits/f3047f34238287416e07b650f8ef04bf8ea93769
- 이미지 src 수정 (images -> Images) - https://github.com/themoment-team/hello-gsm-front/pull/248/commits/aed6bbf6ffbc1cf63dcc4fdf65096931685f494d
- 로그인 성공 시 리다이렉트 처리 추가 - https://github.com/themoment-team/hello-gsm-front/pull/248/commits/900b69873e3e9b11f3f780f112339977d82e7af3
- 회원가입 api 연동(인증번호 발급, 인증번호 확인, 회원가입)
=> [Client] 회원가입 & 로그인 api 연동

packages/hello-gsm-admin/src/PageContainer/TicketPage/index.tsx, packages/hello-gsm-admin/src/Types/application.ts, packages/hello-gsm-admin/src/Types/ticket.ts, packages/hello-gsm-admin/src/Utils/Libs/formatScreening.ts
수험표 날짜 수정, ticket type변경하였습니다
+ 수험표 양식대로 날짜 변경
+ ticket.ts 타입수정
=> [Admin] Edit  ticket date

packages/hello-gsm/src/PageContainer/ChoosePage/index.tsx, packages/hello-gsm/src/PageContainer/ChoosePage/style.ts, packages/hello-gsm/src/components/BubbleButton/style.ts, packages/hello-gsm/src/type/application.ts
> 모의 성적 계산 버튼 위치 조정
- before
- after
=> [Client] Bubble Button top 

packages/hello-gsm/src/PageContainer/SchoolPage/index.tsx, packages/hello-gsm/src/PageContainer/SchoolPage/style.ts
> 취업률 차트에서 연도 클릭시에도 이벤트가 발생하도록 하였습니다.
+ NotCurrentYearText에 이벤트 함수를 연결하였습니다.
+ cursor pointer를 적용했습니다.
=> [Client] graph text click

packages/hello-gsm/src/components/MainPageDescription/index.tsx
오타를 수정하였습니다.
55e7e9c 에서 확인 가능합니다.
=> [Client] fix grammar

packages/hello-gsm/src/components/Modals/FindSchoolModal/index.tsx
> 학교 검색 필터 에러 수정
> 학교 검색 필터 에러 수정
=> [Client] school filter error fix

packages/hello-gsm/src/components/InformationDescription/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx
> 입학 일정 관련 내용을 수정했습니다.
- 선출 -> 발표
- 등기 우편 or 방문 제출 -> 방문 제출
=>  [Client] schedule description

packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/PageContainer/ManualPage/index.tsx, packages/hello-gsm/src/PageContainer/SchoolPage/style.ts, packages/hello-gsm/src/components/FAQBox/style.ts, packages/hello-gsm/src/components/MainPageDescription/style.ts
> 모바일 QA 변경사항을 반영했습니다.
- FAQ 질문 간격 조정 33b1bb3a3b5a4cf2074cd077897ecf0e74a5d156
- 메인 페이지 description 모바일 스타일 7b95757a01ebfc80f20459a8781fde5bef718680
- 학교 소개 모바일 스타일 7b95757a01ebfc80f20459a8781fde5bef718680
- 메뉴얼 페이지 카카오 이미지 추가 9c7d2ed34e3a9de98faeb1001603e144630db524
=> [Client] Mobile QA

packages/hello-gsm-admin/src/Api/application.ts, packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/Types/application.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts
최종제출이 완료된 사용자를 검색하는 api를 제작하였습니다.
+ getSearchApplication 추가
+ searchApplication 추가
=> [Admin] add search application api

packages/hello-gsm/src/PageContainer/ApplicationPage/index.tsx, packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/Utils/Format/formatGender.ts, packages/hello-gsm/src/Utils/Format/formatGraduation.ts, packages/hello-gsm/src/Utils/Format/formatMajor.ts, packages/hello-gsm/src/Utils/Format/formatScreening.ts, packages/hello-gsm/src/components/ApplicantsStatus/index.tsx, packages/hello-gsm/src/components/BubbleButton/style.ts, packages/hello-gsm/src/components/Common/Header/style.ts, packages/hello-gsm/src/pages/_app.tsx, packages/hello-gsm/src/pages/application.tsx, packages/hello-gsm/src/pages/index.tsx, packages/hello-gsm/src/type/application.ts, packages/hello-gsm/src/type/ged.ts
> 원서 출력 페이지 QA, 원서 QA 변경사항을 반영했습니다.
최종 제출 후 https://test.hellogsm.kr/application 에서 확인 가능합니다.
- 검정고시 요청 시 선생님 전화번호 빈 문자열 들어가는 오류 해결 - 292314300977eb118ee8611156dadbf99e47ae3c
- 원서 수정할 때 학교 이름 세팅이 안되어 있음 (서버측 문제인걸로 알아냄) 
- 최종 제출 시 지원 완료 버튼이 보이게 (메인 페이지 ssr을 csr 방식으로 바꾸며 해결.) - 3ba60aedbf38055ab4b31ad8b071b1f33e11f079
- CommonType 타입 수정
- 원서 출력 페이지 ssr -> csr - 65d5f36632385437c9f64c308f38a0275e586c7f
- 원서 페이지 채널톡 제거 - https://github.com/themoment-team/hello-gsm-front/pull/267/commits/b198d514abd22cc3bb8ccd9d3c42d6a8d2aed042
Apply에서 유효성 처리 전에 onNext 로 넘어가 몇몇 값이 누락되어도 성적 페이지로 넘어가는 현상이 발생했습니다.
state로 관리하지 않고 변수로 조건을 관리하여 해당 에러를 해결했습니다.
**에러 상황**
validate함수 요청 전에 apply를 실행하여 onNext가 실행되었음
**해결**
1. validate
2. apply
3. onNext
위와 같은 절차를 수행하며 안전하게 유효성 검사가 됨
관련 커밋: …
=> [Client] Application QA, Apply QA

packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/PageContainer/MainPage/style.ts, packages/hello-gsm-admin/src/Types/searchTag.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts, packages/hello-gsm-admin/src/components/ListHeader/index.tsx, packages/hello-gsm-admin/src/components/ListHeader/style.ts, packages/hello-gsm-admin/src/components/PaginationController/index.tsx, packages/hello-gsm-admin/src/components/SideBar/style.ts
> 검색 기능을 구현했습니다.
+ 검색 태그 타입을 추가했습니다.
+ 검색 태그를 추가하고 API요청 옵션을 설정 했습니다.
검색이 잘 이루어지는지 테스트 부탁드립니다!
=> [Admin] search API

packages/hello-gsm-admin/src/components/PaginationController/index.tsx
페이지네이션 로직을 수정하였습니다.
페이지가 담긴 배열을 돌리는 for문에 조건을 추가하였습니다.
=> [Admin] edit pagination logic

packages/hello-gsm/src/PageContainer/FAQPage/style.ts, packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/style.ts, packages/hello-gsm/src/components/SideBar/style.ts, packages/hello-gsm/src/pages/_app.tsx, packages/hello-gsm/src/pages/apply.tsx
> 인증 페이지에서 전화번호 reset 버튼을 추가했습니다.
- 회원가입 reset 추가
- FAQ default cursor 추가
현재 application 페이지에서 채널톡이 사라지지 않는 이슈가 발생하고 잇습니다. (새로고침 시 사라짐)
일단 해당 pr merge한 뒤 해당 이슈 파악해보고 수정하겠습니다.
=> [Client] SignUp Reset

packages/hello-gsm/src/Assets/svg/HamburgerButton.tsx, packages/hello-gsm/src/PageContainer/FAQPage/style.ts, packages/hello-gsm/src/PageContainer/SignInPage/index.tsx, packages/hello-gsm/src/PageContainer/SignInPage/style.ts, packages/hello-gsm/src/components/FAQBox/style.ts
모바일 반응형을 개선하였습니다.
+ 햄버거 svg 반응형 개선 093e6f6
+ 로그인 버튼속 로고 크기 개선, 자주 묻는 질문 width 개선
=> [Client] 모바일 반응형 개선

packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/Stores/StoreContainer.ts, packages/hello-gsm-admin/src/components/Modal/ModalButton/index.tsx, packages/hello-gsm-admin/src/components/Modal/ModalButton/style.ts, packages/hello-gsm-admin/src/components/Modal/ModalInput/index.tsx, packages/hello-gsm-admin/src/components/Modal/index.tsx
> 상태관리 모달 리팩토링
> 상태관리 모달 버튼 diasbled 추가
=> [Admin] modal refactoring

packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/components/ChannelTalk/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx
> 인증번호 미입력시 에러 추가
> 인증번호 미입력시 에러 추가하였습니다
=> [Client] 인증번호 미입력시 에러 추가

packages/hello-gsm-admin/src/Api/user.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts, packages/hello-gsm-admin/src/pages/index.tsx, packages/hello-gsm-admin/src/type/user.ts
> 관리자 페이지 접속 시 권한을 검증하여 관리자가 아닐 시 로그인 페이지로 이동하게 했습니다.
=> [Admin] SignUp Authority 검증

packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/components/PaginationController/index.tsx, packages/hello-gsm-admin/src/components/PaginationController/style.ts
페이지네이션 스타일수정, 예외처리
- pageNumber가 0이거나 총페이지수보다 많을경우 1로 가도록 예외처리 했습니다
- 스타일 수정
=> [Admin] 페이지네이션 예외처리,스타일 수정

packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx
=> [Client] Fix 접수 날짜 

packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm/src/PageContainer/InformationPage/style.ts, packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/style.ts, packages/hello-gsm/src/hooks/useMiddleware.ts
> QA 변경사항 반영
- 전화번호 정규식 수정
- "지원자 본인만 인증 가능합니다" 추가
- 이중 스크롤 개선
=> [Client] QA 변경사항 반영

packages/hello-gsm-admin/src/Api/application.ts, packages/hello-gsm-admin/src/Utils/Libs/requestUrls.ts, packages/hello-gsm-admin/src/components/ListHeader/index.tsx, packages/hello-gsm-admin/src/components/PrintButton/style.ts
> Excel 버튼 연동
> Excel 버튼 연동하는 로직 추가
=> [Admin] Excel 버튼 연동

packages/hello-gsm/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/GEDCalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/GEDCalculatorPage/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx
> develop에서 누락된 날짜 추가, 성적 피드백 추가
- 검정 고시 예외처리 (성적이 만점보다 높을 경우)
- 일반 학생 성적 입력 시 예외가 있을 경우 피드백 추가
- 날짜 + 요일 추가
=> [Client] Fix Date

packages/hello-gsm/src/PageContainer/InformationPage/style.ts, packages/hello-gsm/src/Utils/Libs/requestApi.ts, packages/hello-gsm/src/middleware.ts
> 인증이 필요없는 페이지에서 로그인 페이지로 이동하는 현상을 막았습니다.
**기존 이슈**  
ex. 인증이 필요없는 페이지인 자주묻는 질문에서 새로고침 하면 로그인 페이지로 이동하는 에러 발생
- interceptor를 특정 예외 URL만 적용시키게 변경 하였음
- Middleware 적용
=> [Client] Fix Interceptor

packages/hello-gsm/vercel.json
vercel로 배포시 새로고침, 페이지 뒤로가기시 404가뜨는 오류를 해결하였습니다.
- vercel.json 추가
=> Update vercel 404 오류

packages/hello-gsm-admin/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm-calculate/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/CalculatorPage/index.tsx
> 예체능 최소값 입력.
예체능 모든 값을 '없음'이라고 선택하면 NaN이라고 나오는 에러를 해결
=> [Client] artSportsScore defaultValue

packages/hello-gsm/src/PageContainer/SignUpPage/index.tsx, packages/hello-gsm/src/PageContainer/SignUpPage/style.ts
> subtitle 위치 조정
>  subtitle 위치 조정
=> [Client]  subtitle 위치 조정

packages/hello-gsm-admin/src/PageContainer/TicketPage/style.ts, packages/hello-gsm-admin/src/pages/ticket.tsx
> ticket layout을 고쳤습니다.
- ticket api 에러 시 메인 페이지로 이동
- 수험표 레이아웃 조정
=> [Admin] Update Ticket Layout

packages/hello-gsm/src/middleware.ts, packages/hello-gsm/src/pages/_app.tsx
> 구글 시트로 점검창을 관리했습니다.
확인이 완료되면 production에도 적용할 수 있게 환경을 구축하겠습니다.
=> [Client] Sheet Inspection

packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/style.ts, packages/hello-gsm/src/components/BubbleButton/style.ts
> 메인 페이지에 입학 가이드 확인 경로를 추가했습니다.
- pdf 추가
- 메인 페이지 접근 UI 추가
=> [Client] Add Guide

packages/hello-gsm/src/PageContainer/InformationPage/index.tsx, packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/components/ChannelTalk/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx
> 메인 페이지 내용을 수정했습니다.
- 채널톡 설정 변경
- 메인 페이지 내용 수정
=> [Client] Update MainPage content

packages/hello-gsm/src/components/InformationDescription/index.tsx
입학 절차 문구수정하였습니다.
- 문구수정 cd98afd
=> [Hotfix] 입학 절차 문구 수정

packages/hello-gsm/src/components/MainPageDescription/index.tsx
메인페이지 입학 원서 제출 문구 수정
- 메인페이지 입학 원서 제출 문구 수정 ff79705
=> [Hotfix] 메인페이지 입학 원서 제출 문구 수정

packages/hello-gsm/src/PageContainer/MypagePage/index.tsx, packages/hello-gsm/src/hooks/useMiddleware.ts, packages/hello-gsm/src/pages/application.tsx
> 원서 출력 버튼 추가
원서 출력 버튼 추가하였습니다.
- mypage에 최종제출 전 원서 미리보기 버튼 추가
- application에 최종제출을 해야 페이지 접근이 가능한 코드 삭제
=> [Hotfix] 원서 출력 버튼 추가

packages/hello-gsm-admin/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm-admin/src/components/Apply/ApplyBarBox/index.tsx, packages/hello-gsm/src/PageContainer/ApplyPage/index.tsx, packages/hello-gsm/src/components/ApplyBarBox/index.tsx
=> [Hotfix] phone number

packages/hello-gsm-admin/src/PageContainer/ApplyPage/index.tsx
=> [Hotfix] 정규식 수정

packages/hello-gsm-admin/src/PageContainer/ApplicationPage/index.tsx
어드민 날짜 에러 수정
- 어드민 날짜 에러 수정 70ddcb7
=> [Hotfix] 어드민 날짜 에러 수정

packages/hello-gsm-admin/src/PageContainer/ApplicationPage/index.tsx, packages/hello-gsm-admin/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm-calculate/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/ApplicationPage/index.tsx, packages/hello-gsm/src/PageContainer/CalculatorPage/index.tsx, packages/hello-gsm/src/PageContainer/Test/CalculatorPage/index.tsx
성적 입력창 -> 비교과 출결상황을 -> 미인정 출결 현황로 변경하였습니다.
- 작업내용 036baa6
=> [Client] 성적입력창 수정

packages/hello-gsm/src/PageContainer/MypagePage/index.tsx, packages/hello-gsm/src/PageContainer/MypagePage/style.ts, packages/hello-gsm/src/components/Modals/MypageModal/index.tsx, packages/hello-gsm/src/components/Modals/MypageModal/style.ts
> 최종 제출 모달 원서 미리보기 버튼 추가
- 최종 제출 모달 원서 미리보기 버튼 추가
- 마이페이지 버튼 박스 width 수정
=> [Client] 최종 제출 모달 원서 미리보기 버튼 추가

packages/hello-gsm/src/components/Common/Header/index.tsx
로그아웃 중복 클릭을 막았습니다.
작업내용 a70584a
=> [Client] 로그아웃 중복클릭 막기

packages/hello-gsm-admin/src/PageContainer/ApplicationPage/index.tsx, packages/hello-gsm-admin/src/PageContainer/ApplyPage/index.tsx
> admin 생년월일 표기 오류 수정했습니다.
- 원서 출력 시, 생년월일의 월이 +1 되는 현상 수정
- 원서 수정 시, 생년월일의 월이 -1 되는 현상 수정
=> [Hotfix] Admin 생년월일 부 에러 수정

packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx
어드민페이지 지원자리스트 미제출과 제출을 나누어서 정렬하였습니다.
- 작업내용 71ab3df
=> [Hotfix] 어드민 지원자리스트 정렬

packages/hello-gsm-admin/src/PageContainer/MainPage/index.tsx, packages/hello-gsm-admin/src/components/ContentBox/index.tsx, packages/hello-gsm-admin/src/components/Modal/index.tsx, packages/hello-gsm-admin/src/type/application.ts
> registrationNumber 변수에 userId 값이 들어가는 오류 해결
> registrationNumber 변수에 userId 값이 들어가는 오류 해결하였습니다
=> [Hotfix] registrationNumber 수정

packages/hello-gsm/src/components/Modals/MainResultModal/index.tsx
=> [Client] 학과 색상 변경

packages/hello-gsm/src/PageContainer/MainPage/index.tsx, packages/hello-gsm/src/components/Common/Header/index.tsx, packages/hello-gsm/src/components/MainPageDescription/index.tsx, packages/hello-gsm/src/components/Modals/MainResultModal/style.ts, packages/hello-gsm/src/middleware.ts, packages/hello-gsm/src/shared/Date/afterApply.ts, packages/hello-gsm/src/shared/Date/firstScreening.ts
> serviceEnd
- 로그인 버튼 삭제
- 결과 확인을 위해 로그인 해주세요 모달 X
- `auth/signin` url 접근 X (아직 확인 중 입니다)
- 메인페이지 하단 결과 발표 확인을 위해선 로그인이 필요합니다 변경
=> [Client] serviceEnd

packages/hello-gsm/src/components/Common/Header/index.tsx, packages/hello-gsm/src/components/Common/Header/style.ts, packages/hello-gsm/src/components/SideBar/style.ts
> @yebin0310 님께서 찾아주신 hydration 에러를 해결했습니다.
`import { NavContent } from 'components/Common/Header/style';`
<- 위 코드와 같이 스타일간의 의존성이 너무 커서 새로 생성하였습니다.
=> Fix hydration error

packages/hello-gsm/src/components/Common/SEOHelmet/index.tsx
> metadata의 title을 요구사항에 따라 변경했습니다.
Hello, GSM -> 광주소프트웨어마이스터고등학교 신입생 입학 지원 서비스
로 변경하였습니다.
=> Update metadata title
